const HOMEPAGE_MENU_TOGGLE = "HOMEPAGE_MENU_TOGGLE";
const SETTING_TOGGLE = "SETTING_TOGGLE";
const SETTING_FONT_TOGGLE = "SETTING_FONT_TOGGLE";
const SETTING_COLOR_TOGGLE = "SETTING_COLOR_TOGGLE";

export {
  HOMEPAGE_MENU_TOGGLE,
  SETTING_TOGGLE,
  SETTING_FONT_TOGGLE,
  SETTING_COLOR_TOGGLE,
};
