const HOMEPAGE_MENU_TOGGLE = "HOMEPAGE_MENU_TOGGLE";
const SETTING_TOGGLE = "SETTING_TOGGLE";
const SETTING_FONT_TOGGLE = "SETTING_FONT_TOGGLE";
const SETTING_COLOR_TOGGLE = "SETTING_COLOR_TOGGLE";
const SETTING_FORM_SUBMIT = "SETTING_FORM_SUBMIT";

export {
  HOMEPAGE_MENU_TOGGLE,
  SETTING_TOGGLE,
  SETTING_FONT_TOGGLE,
  SETTING_COLOR_TOGGLE,
  SETTING_FORM_SUBMIT,
};
